name: "Setup"
description: "Setup"
inputs:
  mix-env:
    description: "Mix env"
    required: true
    default: ""
runs:
  using: "composite"
  steps:
    - name: Setup Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: "1.13.1"
        otp-version: "24.2"

    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Restore build cache
      uses: actions/cache@v3
      with:
        path: _build
        key: ${{ runner.os }}-build-elixir-${{ inputs.mix-env }}
        restore-keys: ${{ runner.os }}-build-elixir-${{ inputs.mix-env }}

    - name: build
      run: |
        mix deps.get --only ${{ inputs.mix-env }}
        mix compile --warnings-as-errors
      shell: bash
