name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Deploy
        run: echo ${{ inputs.environment }}
