name: New Version

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: New Version
        required: true

jobs:
  push_tag:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.TAG_PUSH_TOKEN }}

      - name: Git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Print Version
        run: echo "${{ github.event.inputs.version }}"

      - name: Git Push
        run: |
          git tag -a ${{ github.event.inputs.version }} -m "release ${{ github.event.inputs.version }}"
          git push --follow-tags

  deploy-hom:
    needs: bump_version
    uses: ./.github/workflows/deploy.yml
    with:
      environment: hom

  deploy-prod:
    needs: deploy-hom
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
