name: New Version

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: New Version
        required: true

jobs:
  bump_version:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.TAG_PUSH_TOKEN }}

      - name: Setup
        uses: ./.github/actions/setup
        with:
          mix-env: dev

      - name: Git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Print Version
        run: echo "${{ github.event.inputs.version }}"

      - name: Bump Version
        run: mix bump_version ${{ github.event.inputs.version }}

      - name: Git Push
        run: |
          git add mix.exs
          git commit -m "Bump version to ${{ github.event.inputs.version }}"
          git tag -a ${{ github.event.inputs.version }} -m "release ${{ github.event.inputs.version }}"
          git push --follow-tags

  deploy-hom:
    needs: bump_version
    uses: ./.github/workflows/deploy.yml
    with:
      environment: hom

  deploy-prod:
    needs: deploy-hom
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
