name: New Version

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: New Version
        required: true

jobs:
  push_tag:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.TAG_PUSH_TOKEN }}

      - name: Git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Calver Release
        uses: StephaneBour/actions-calver@master
        id: calver
        with:
          date_format: "%y.%m"
          release: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Git Push
        env:
          VERSION: ${{ steps.calver.outputs.release }}
        run: |
          git tag -a ${VERSION} -m "release ${VERSION}"
          git push --follow-tags

  deploy-hom:
    needs: push_tag
    uses: ./.github/workflows/deploy.yml
    with:
      environment: hom

  deploy-prod:
    needs: deploy-hom
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
